#!/bin/sh
sudo pacman -S $(cat package.list| cut -d' ' -f1) --noconfirm
#!/bin/sh

# Install ZSH, OMZ
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc && \

# Setup Dracula Theme
curl https://raw.githubusercontent.com/mafredri/zsh-async/master/async.zsh -o ~/.oh-my-zsh/themes/lib/async.zsh --create-dirs && \ 
git clone https://github.com/dracula/zsh.git /tmp/zsh && \
cp /tmp/zsh/dracula.zsh-theme ~/.oh-my-zsh/themes && \

# Install Plugins
sudo git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
sudo git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

