session_name: website_dev
windows:
  - window_name: dev window
    layout: tiled
    shell_command_before:
      - cd ~/Desktop/indebted-website && clear
    panes:
      - yarn dev
      - ls
      - gitui
