import = ["/Users/c/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

[font]
size = 16
builtin_box_drawing = false

[font.bold]
family = "SpaceMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "SpaceMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "SpaceMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "SpaceMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9
decorations = "None"
blur = true
