import = ["/Users/c/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

[font]
size = 16
builtin_box_drawing = true

[font.bold]
family = "MartianMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MartianMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MartianMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "MartianMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 2

[window]
opacity = 0.8
decorations = "None"

[window.padding]
x = 4
y = 4
