[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
opacity = 0.9
decorations = "None"

[env]
TERM = "xterm-256color"

[font]
size = 16
normal = { family = "VictorMono Nerd Font Mono", style = "Regular" }
bold = { family = "VictorMono Nerd Font Mono", style = "Bold" }
italic = { family = "VictorMono Nerd Font Mono", style = "Medium Italic" }
bold_italic = { family = "VictorMono Nerd Font Mono", style = "Bold Italic" }
builtin_box_drawing = false

